import { Character, CharacterStatus, Gender } from '../models';

export const characterMock: Character[] = [
  {
    id: 1,
    name: 'Rick Sanchez',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: 'Scientist',
    gender: Gender.Male,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/2',
    ],
  },
  {
    id: 2,
    name: 'Morty Smith',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: '',
    gender: Gender.Male,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/3',
    ],
  },
  {
    id: 3,
    name: 'Beth Smith',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: '',
    gender: Gender.Female,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/4',
    ],
  },
  {
    id: 4,
    name: 'Jerry Smith',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: '',
    gender: Gender.Male,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/2',
      'https://rickandmortyapi.com/api/episode/5',
    ],
  },
  {
    id: 5,
    name: 'Summer Smith',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: '',
    gender: Gender.Female,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/6',
    ],
  },
  {
    id: 6,
    name: 'Birdperson',
    status: CharacterStatus.Alive,
    species: 'Birdperson',
    type: '',
    gender: Gender.Male,
    origin: 'Bird World',
    location: 'Bird World',
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/3',
      'https://rickandmortyapi.com/api/episode/4',
    ],
  },
  {
    id: 7,
    name: 'Mr. Meeseeks',
    status: CharacterStatus.Alive,
    species: 'Meeseeks',
    type: '',
    gender: Gender.Male,
    origin: 'Meeseeks Box',
    location: 'Meeseeks Box',
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
    ],
  },
  {
    id: 8,
    name: 'Squanchy',
    status: CharacterStatus.Alive,
    species: 'Feline',
    type: '',
    gender: Gender.Male,
    origin: 'Squanchy Planet',
    location: 'Squanchy Planet',
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/2',
      'https://rickandmortyapi.com/api/episode/5',
    ],
  },
  {
    id: 9,
    name: 'Evil Morty',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: 'Clone',
    gender: Gender.Male,
    origin: 'Unknown',
    location: 'Unknown',
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/9',
      'https://rickandmortyapi.com/api/episode/10',
    ],
  },
  {
    id: 10,
    name: 'Tina',
    status: CharacterStatus.Dead,
    species: 'Human',
    type: '',
    gender: Gender.Female,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/7',
    ],
  },
  {
    id: 11,
    name: 'Purge',
    status: CharacterStatus.Dead,
    species: 'Unknown',
    type: '',
    gender: Gender.Unknown,
    origin: 'Purge Planet',
    location: 'Purge Planet',
    image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/4',
      'https://rickandmortyapi.com/api/episode/5',
    ],
  },
  {
    id: 12,
    name: 'Krombopulos Michael',
    status: CharacterStatus.Dead,
    species: 'Gromflomite',
    type: '',
    gender: Gender.Male,
    origin: 'Gromflom Prime',
    location: 'Gromflom Prime',
    image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
    ],
  },
  {
    id: 13,
    name: 'Fart',
    status: CharacterStatus.Unknown,
    species: 'Gas Being',
    type: '',
    gender: Gender.Unknown,
    origin: 'Fart Dimension',
    location: 'Fart Dimension',
    image: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/6'],
  },
  {
    id: 14,
    name: 'Scary Terry',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: 'Nightmare',
    gender: Gender.Male,
    origin: 'Nightmare Dimension',
    location: 'Nightmare Dimension',
    image: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/3',
      'https://rickandmortyapi.com/api/episode/9',
    ],
  },
  {
    id: 15,
    name: 'The Narrator',
    status: CharacterStatus.Unknown,
    species: 'Human',
    type: '',
    gender: Gender.Male,
    origin: 'Unknown',
    location: 'Unknown',
    image: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/10'],
  },
  {
    id: 16,
    name: 'King Jellybean',
    status: CharacterStatus.Dead,
    species: 'Jellybean',
    type: '',
    gender: Gender.Male,
    origin: 'Candy Land',
    location: 'Candy Land',
    image: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/11'],
  },
  {
    id: 17,
    name: 'Meeseeks Box',
    status: CharacterStatus.Unknown,
    species: 'Meeseeks',
    type: '',
    gender: Gender.Unknown,
    origin: 'Meeseeks Box',
    location: 'Meeseeks Box',
    image: 'https://rickandmortyapi.com/api/character/avatar/17.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/8'],
  },
  {
    id: 18,
    name: 'Jessica',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: '',
    gender: Gender.Female,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/12'],
  },
  {
    id: 19,
    name: 'Mr. Poopybutthole',
    status: CharacterStatus.Alive,
    species: 'Human',
    type: '',
    gender: Gender.Male,
    origin: 'Earth (C-137)',
    location: 'Earth (C-137)',
    image: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/2',
      'https://rickandmortyapi.com/api/episode/6',
    ],
  },
  {
    id: 20,
    name: 'Squidward',
    status: CharacterStatus.Alive,
    species: 'Squid',
    type: '',
    gender: Gender.Male,
    origin: 'Squid World',
    location: 'Squid World',
    image: 'https://rickandmortyapi.com/api/character/avatar/20.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/5',
      'https://rickandmortyapi.com/api/episode/6',
    ],
  },
];
