import { CharacterDto } from '../models/characterDto';
import { ResponseDto } from '../models/responseDto';

const characters: CharacterDto[] = [
  {
    id: 1,
    name: 'Rick Sanchez',
    status: 'Alive',
    species: 'Human',
    type: 'Scientist',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/1',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 2,
    name: 'Morty Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Teenager',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Anatomy_Park',
      'https://rickandmorty.fandom.com/wiki/Morty%E2%80%99s_Mind_Blowers',
    ],
    url: 'https://rickandmortyapi.com/api/character/2',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 3,
    name: 'Summer Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Teenager',
    gender: 'Female',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Summer_Morty_Adventures',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/3',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 4,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Surgeon',
    gender: 'Female',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
    ],
    url: 'https://rickandmortyapi.com/api/character/4',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 5,
    name: 'Jerry Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Househusband',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Ricklantis_Mixup',
    ],
    url: 'https://rickandmortyapi.com/api/character/5',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 6,
    name: 'Birdperson',
    status: 'Alive',
    species: 'Birdperson',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Birdperson',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Birdperson',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/Rest_and_Ricklaxation',
    ],
    url: 'https://rickandmortyapi.com/api/character/6',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 7,
    name: 'Mr. Poopybutthole',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Poopybutthole',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Poopybutthole',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/Rest_and_Ricklaxation',
    ],
    url: 'https://rickandmortyapi.com/api/character/7',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 8,
    name: 'Squanchy',
    status: 'Alive',
    species: 'Catperson',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Squanchy',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Squanchy',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
      'https://rickandmorty.fandom.com/wiki/The_Ricklantis_Mixup',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/8',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 9,
    name: 'Mr. Meeseeks',
    status: 'Alive',
    species: 'Meeseeks',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Meeseeks',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Meeseeks',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Meeseeks_and_Destroy',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/9',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 10,
    name: 'Evil Morty',
    status: 'Alive',
    species: 'Human',
    type: 'Evil Version',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Evil_Morty',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Evil_Morty',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Ricklantis_Mixup',
      'https://rickandmorty.fandom.com/wiki/Rest_and_Ricklaxation',
    ],
    url: 'https://rickandmortyapi.com/api/character/10',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 1,
    name: 'Rick Sanchez',
    status: 'Alive',
    species: 'Human',
    type: 'Scientist',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/1',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 2,
    name: 'Morty Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Teenager',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Anatomy_Park',
      'https://rickandmorty.fandom.com/wiki/Morty%E2%80%99s_Mind_Blowers',
    ],
    url: 'https://rickandmortyapi.com/api/character/2',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 3,
    name: 'Summer Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Teenager',
    gender: 'Female',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Summer_Morty_Adventures',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/3',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 4,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Surgeon',
    gender: 'Female',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
    ],
    url: 'https://rickandmortyapi.com/api/character/4',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 5,
    name: 'Jerry Smith',
    status: 'Alive',
    species: 'Human',
    type: 'Househusband',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    location: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Earth_(Dimension_C-137)',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Ricksy_Business',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Ricklantis_Mixup',
    ],
    url: 'https://rickandmortyapi.com/api/character/5',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 6,
    name: 'Birdperson',
    status: 'Alive',
    species: 'Birdperson',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Birdperson',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Birdperson',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/Rest_and_Ricklaxation',
    ],
    url: 'https://rickandmortyapi.com/api/character/6',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 7,
    name: 'Mr. Poopybutthole',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Poopybutthole',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Poopybutthole',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/Rest_and_Ricklaxation',
    ],
    url: 'https://rickandmortyapi.com/api/character/7',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 8,
    name: 'Squanchy',
    status: 'Alive',
    species: 'Catperson',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Squanchy',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Squanchy',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Total_Rickall',
      'https://rickandmorty.fandom.com/wiki/The_Ricklantis_Mixup',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/8',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 9,
    name: 'Mr. Meeseeks',
    status: 'Alive',
    species: 'Meeseeks',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Meeseeks',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Mr._Meeseeks',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Meeseeks_and_Destroy',
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Pickle_Rick',
    ],
    url: 'https://rickandmortyapi.com/api/character/9',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 10,
    name: 'Evil Morty',
    status: 'Alive',
    species: 'Human',
    type: 'Evil Version',
    gender: 'Male',
    origin: {
      name: 'Earth (Dimension C-137)',
      link: 'https://rickandmorty.fandom.com/wiki/Evil_Morty',
    },
    location: {
      name: 'Unknown',
      link: 'https://rickandmorty.fandom.com/wiki/Evil_Morty',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    episode: [
      'https://rickandmorty.fandom.com/wiki/Close_Rick-Counters_of_the_Rick_Kind',
      'https://rickandmorty.fandom.com/wiki/The_Ricklantis_Mixup',
      'https://rickandmorty.fandom.com/wiki/Rest_and_Ricklaxation',
    ],
    url: 'https://rickandmortyapi.com/api/character/10',
    created: '2017-11-04T18:48:46.250Z',
  },
  // More mock data can follow the same pattern...
];

export const mockResponse: ResponseDto = {
  info: {
    count: 20,
    pages: 1,
    next: '',
    prev: '',
  },
  results: [...characters],
};
